title: Nikki Nadarevic
tagline: Engineering Student
description: Personal website and CV
url: "https://yourusername.github.io"

theme: cvless

author:
  name: Nikki Nadarevic
  email: your-email@example.com
